[[mapping]]
folder = "PDF"
glob = "*.pdf"

[[mapping]]
folder = "/home/jmgduarte/Pictures"
glob = "*.jpg"

[[mapping]]
folder = "/home/jmgduarte/Pictures"
glob = "*.png"

[[mapping]]
folder = "compressed"
glob = "*.zip"

[[mapping]]
folder = "compressed"
glob = "*.tar*"

[[mapping]]
folder = "packages"
glob = "*.deb"

[[mapping]]
folder = "scripts"
glob = "*.sh"