[[mapping]]
folder = "RAW"
glob = "./**/*.raf*"

[[mapping]]
folder = "JPG"
glob = "./**/*.jpg"

# [[mapping]]
# folder = "empty"
# glob = ".non_existent"

# [[mapping]]
# folder = "JPG"
# glob = "/*.jpg"
# name = "{{ORIGINAL}}_{{DATE}}.{{EXT}}"
